###Counting DNA Nucleotides
INPUT = "GTTTGAATTCCCAAAGACGCGCAAAACAAAAAAGCATCAGGCATCCCGCGGGTTATTTTACAGAATCGCCATGTCGACGGCCGAATATAACACAAGCCCACCGGTGATGGAGGGGTCGCGACATGGCTCCTTCCGCTAAACTGTAAACGCCCGTTGCATGATTCCTAGTGCGTCGCAAGACAGCCACAGACGAGTAAATGGCCCTACGTCTTCCAGGCGTGCCAGCCGAGAGAGGCTCGAGAAGGTAGAACCTATCTAGGGTTGACTCTAACATGTTGAAGCACGTCGCCTCGAAGACCACTCTCGTCGCCCAAATTATGATCGCATCGTATGAGGACTGAATCAATGCTTACCCGACTGGCCGCCTAAACAAACGACGAAGCCCATGAAACGCTACGTACGCTCTGAGGTATGGGTTATTTAAGTCAGACAACTCCTCCTCGGTATATCATAGGTTAAGCGCACTAACCCTCAAGACAAAACGCGGGAGACCGACGCATCTACAGCGTACGTCCGTAACACATCCAAGCAGACGATAAACTTCCAATTCCGACATTATGACCGGTCCTCTGAAAGAACTCATATATCCTGCCGGGCTGAGCCGTACCTACGAGCCACAGACGTTAATCAAATTCTAATCAACCGACGGCTTTCTTGCGATTTTGACACGTTTTAGCTTAAAGATGGCGGTCCTCCACGCAGTGCCTATGGCGAGGCATGGGGCGCTATACCAAGGTGCACCATGCAACGTATAAAGAATGGGCCTCTTCGATGGAGTAAGGTGGCAATACATGTTAGGCACTTGACGTTTACAGAGTAGTGCGCGCGCAGATTGAAATTGGCCAGTCCCGGACGATAATTCAATGAGCATTAGAGTTGCCCCACAGAATACCGTGGATTCGCAAGACATT"
count_A=0
count_T=0
count_C=0
count_G=0
for chr in INPUT:
    if chr == "A":
        count_A+=1
    elif chr == "T":
        count_T+=1
    elif chr == "C":
        count_C+=1
    elif chr == "G":
        count_G+=1
print count_A,count_C,count_G,count_T
