####Inferring mRNA from Protein
##the codon table is from: http://www.petercollingridge.co.uk/python-bioinformatics-tools/codon-table  by Peter Collingridge
bases = ['U', 'C', 'A', 'G']
codons = [a+b+c for a in bases for b in bases for c in bases]
amino_acids = 'FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG'
codon_table = dict(zip(codons, amino_acids))
AA_count = {}
for key,val in codon_table.items():
    AA_count.setdefault(val,[]).append(key)
for key in AA_count.keys():
    AA_count[key] = len(AA_count[key])
##########
INPUT = '''MEAFDGICVDYTFDDRETRSLPWWWPTMFVQEQHQAWWSTRFRQGLADKGPMAMPCFFQGEMHAVEVTGHHDERKHAYYQWNGQTANTFQWINRMLHFIEDRFKIPELRRIFHDLQSEAYMWASRQRALCYMWMPGFLNKRSVAQNRTCVHSYFFHSGQHEEDQCHENGRGPYGNNYYPGGFCFHSVLPDCRRVSKMHMFHSLYMEFFFDKMELQIGPRGDKAMIFMPRPGNESIITKWVEWKEIVGGNLQFYCMPLHLPQAWHKMAVYQFDKRCDTKMWNQAPHNIMINQTVDAGWWCCSCHQFHVFKTSQEQLWAMLKYEGSWNEEEKADRTYKCFWQLDPFYERSEDYVQHVWFSPWGFNELKTGIQRKGPGYVFLVCEIAVAYNSEQHKAAANDVMVQAVSKADADHPKEKSVCSCEDQFSCQDQPLEKLECPKFAMLEEFCYKMSEIEHVKSKCRRENSDMWGGVRKTVGGEWEMHAHVKPCMVECNKNMVSYAHVKEEFMDVDFGAPNVTCEKDAKDFAAMYPQMFHETTCTCPPAVIPDFVVRRSFEDRGCLVYQVGHVVLRMKCGWKVQQEQTVGRCWKQGYCIEAFCAQEYYEEYHVTVWFWGIDAKVSNRVVQVPNQTDECVDIHEYVQVPVASGDNNFAWQTPQGHWDPEYTGFAYKNETEVRRWGGLMAIEPNFKLCLGKLNIIVLFKCMTDQQQTFVSSDFPNTFWIGDIIGYTTQVHSGGTGVPDNITWYFILPGVVHGPIRFILSWKWSISMSVAMHPRYENHFYYEGYPYQPIPCSMCPIQGHDMIKTTRQHIFTAQYTDDETWAGAHQSKWTQLAWRMPNLVFEHLTFHLPKYDVGAFIQDENFAPYVWPLMGMRGCCARSSTQVKHRQNIRMLIPISHAVAGVGIGNQCEIMNILTFWHALGKIFWGNSGGIEVSQFRNKVKKCCWNRTEQNWVLMMGEYMCTMFGAQTDVLVSHAGSGLFTSKSVPCGYCCSNEDWFSTVL'''
RES = 1
for cr in INPUT:
    RES = RES*AA_count[cr]
RES = RES*AA_count['*']
RES = RES%1000000
print RES